import Image from "next/image"
import Link from "next/link";

export const metadata = {
    title: "CARE",
    description: "Generated by create next app",
};

export default function page() {
  return (
    <div>
        <nav className='w-full py-1 px-2 z-30 fixed bg-[#365678] almost:shadow-darks'>
            <div className="flex justify-between max-w-7xl m-auto p-1">

                <span className='font-semibold flex items-center'>
                    <Image src={"/care-logo.png"} alt='logo' className='block' width={50} height={50}></Image>
                </span>

                <div className={`flex justify-center items-center text-white gap-10 font-medium`}>
                    <Link href="/">Home</Link>
                    <Link href="/">About</Link>
                    <Link href="/">Departments</Link>
                    <Link href="/">Billing & info</Link>
                    <Link href="/">Emergency</Link>
                </div>

                <div className='flex items-center justify-center gap-5 text-sm'>
                    <Link href="/login" className='text-black bg-[#E6F2F5] px-5 py-2 font-medium rounded-md hover:bg-[#c6d0d3] transition-colors tracking-wide'>Sign in</Link>
                </div>
            </div>
        </nav>

        <section className='max-w-full m-auto'>
            <div className='relative w-full h-[550px] bg-no-repeat bg-cover bg-center bg-[url("/background.png")]'>
                <div className='text-white z-30 pt-[12rem] flex flex-col justify-center items-center max-w-[600px] m-auto text-center'>
                    <p className='text-3xl sm:text-4xl base:text-5xl xlarge:text-6xl font-bold relative'>Welcome to Clinical Access and Records Expert (CARE)</p>
                    <p className='text-base sm:text-xl font-semibold'>We innovate to make things easier for you.</p>
                    <button className='text-[#09407A] bg-[#E6F2F5] hover:bg-[#c8d3d6] py-2.5 px-5 font-bold rounded-xl mt-5 transition-colors'>Book an Appointment</button>
                </div>
            </div>
      </section>
    </div>
  )
}